name: lzma
version: 1.1.0
homepage: https://github.com/jcmellado/dart-lzma
description: LZMA compression library written in pure dart. Use this library to compress and decompress using the LZMA algorithm.
environment:
  sdk: '>=2.12.0 <4.0.0'
dependencies:
  fixnum: ^1.0.1
dev_dependencies:
  lint: ^2.1.2
  test: ^1.24.3
